version: "3.7"
services:
  php:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - internal_network

  db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: casafy_db
      MYSQL_ROOT_PASSWORD: casafy_root_password
      MYSQL_PASSWORD: casafy_password
      MYSQL_USER: casafy_user
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - internal_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  dbdata: